ic_facebook.ic_facebook_entity_type.*:
  type: config_entity
  label: 'IC Facebook Entity type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
