product_card_demo_block:
  title: Product Card Component
  content:
    lead: Add a quick description here.
    summary: Add code examples here using <code>html code syntax</code>

product_card:
  example_var: This is an example var

