node:
  invoice:
    path: /invoice
  message:
    path: /inbox
global:
  use_on:
    - front
    - backoffice
commerce_store:
  online:
    path: /dashboard
commerce_product_variation:
  default:
    path: /products
