product_content_demo_block:
  title: Product Content Component
  content:
    lead: Add a quick description here.
    summary: Add code examples here using <code>html code syntax</code>

product_content:
  example_var: This is an example var

